export const API_URL = "https://dev-api.gettonote.com/api/v1/";

export const initalUserValues = {
  access_locker_documents: false,
  address: "",
  avatar: "",
  bvn: 0,
  city: "",
  country: "",
  created_at: "",
  dob: "",
  drivers_license_no: "",
  email: "",
  first_name: "",
  gender: "",
  id: "",
  identity_number: "",
  identity_type: "",
  image: "",
  initials: "",
  ip_address: "",
  is_complete: false,
  is_online: false,
  last_name: "",
  national_verification: false,
  nin: "",
  permissions: [],
  phone: "",
  role: [],
  state: "",
  system_verification: false,
  updated_at: "",
};
